### ISSUE TITLE
Addition of CODECOV_TOKEN for eclipse-kuksa

### ISSUE THREAD

**Issue by erikbosch** [eclipse-kuksa/.eclipsefdn#26]
[Kuksa-databroker](https://github.com/eclipse-kuksa/kuksa-databroker/blob/main/.github/workflows/kuksa_databroker_build.yml#L89) uses `codecov-action@v3`. To use v4 we need a secret `secrets.CODECOV_TOKEN`. As of today we only use codecov in that particular repo, but it may in the future be used by other repos so maybe it should better be added as a `orgs.newOrgSecret` in this repository.

As I understand it adding it as not as easy as just creating a PR for https://github.com/eclipse-kuksa/.eclipsefdn/blob/main/otterdog/eclipse-kuksa.jsonnet as some admin activities to define/set the token is needed as well. Admins - does this issue provide sufficient information, or should we better request the change by some other mechanism, like a support ticket?

References:

-  Issue in kuksa-databroker: https://github.com/eclipse-kuksa/kuksa-databroker/issues/11
- Similar Eclipse support ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4546
- Codecov info on token: https://docs.codecov.com/docs/codecov-uploader#organization-upload-token

FYI @SebastianSchildt @bs-jokri

**Comment by SebastianSchildt** [comment]
here is another example ticket https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4391

The main point is, somebody who is taking this task should also make the ticket at Eclipse help desk, because then he/she also gets notified. Especially if except the mechanical task of creating the token, there is more tech support needed afterwards.  If I (or @bs-jokri ) is doing it, but we are NOT the ones integrating it here in CI, that is inconvenient communication-wise.

Anyone of you (with an Eclipse account) can make tickets in the Gitlab issue tracker of eclipsefdn. For requests like this it may be they ask, if project leads support this. In that case reach out to me or @bs-jokri and we will add to the ticket

**Comment by erikbosch** [comment]
Issue created at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4631

**Comment by erikbosch** [comment]
@SebastianSchildt - will be fixed by #27

**Comment by erikbosch** [comment]
Fixed
